---
language: "python"
python:
  - "3.7"

# Install required python packages
install:
  - "pip install -r requirements.txt"

# Perform pre-checks of source code (don't lint the lambda function)
before_script:
  - "pylint polls.py"
  - "black -l 82 --check *.py"

# Perform poll collection testing
script:
  - "python polls.py"
...
